replicaCount: 2

image:
  repository: ghcr.io/deepk-kumar/churn-api
  tag: "latest"          # CI har build par isko commit-sha se badal deta hai
  pullPolicy: IfNotPresent

chaos:
  enabled: false         # true karoge to /chaos/* endpoints khulte hain (sirf demo)

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
